version: '3.8'

services:
  waitlist-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/data/waitlist.db
      - CORS_ORIGINS=*
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
